# Generated by Django 4.2.7 on 2025-05-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_categoria_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoriaa',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='fabricantee',
            new_name='fabricante',
        ),
    ]
